var wallSurface, backgroundSurface;//->Ditto->//{"operation":"define_global_vars"}
pb2GameWorld.DownloadModules( { user_data_uids_to_load: [ 183/*Eric Gurt's Basic trigger action presets*/ ], inline: true, success_callback: _pb2N } );function _pb2N(){//->Ditto->//{"id":"","operation":"create","constructor":"pb2GameWorld.DownloadModules","user_data_uids_to_load":"[ 183/*Eric Gurt's Basic trigger action presets*/ ]","execute_on_load":"true","inline":"true","success_callback":"null","error_callback":"null","x":"0","y":"0","_visible":"0","_locked":"0","_disabled":"0"}
pb2GameWorld.EnableSimplePlayerAssignmentLogic();//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.EnableSimplePlayerAssignmentLogic","argument_values":"","keep_at_the_bottom":"0","_visible":"0","_locked":"0","_disabled":"0"}

/* 
    This script changes the current setting such that it closely resembles PB2 settings. 
    You may remove this script if desired.
*/
pb2GunDisposer.normal_time_to_live=Infinity;
pb2RagdollDisposer.normal_time_to_live=Infinity;
pb2Bullet.friction_wall=0.5;
//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    This script changes the current setting such that it closely resembles PB2 settings. \n    You may remove this script if desired.\n*/\npb2GunDisposer.normal_time_to_live=Infinity;\npb2RagdollDisposer.normal_time_to_live=Infinity;\npb2Bullet.friction_wall=0.5;\n","x":"-810","y":"-530","_visible":"1","_locked":"0","_disabled":"0"}
wallSurface = pb2SurfaceType.CreateSurfaceType({ geometry_type: pb2SurfaceType.TYPE_PB2PLATFORM_WALL, texture_container: pb2Texture.GetTextureByName('pb2platform_texture'), terrain_generation: false, is_for_wall: true, shader_type: pb2SurfaceType.SHADER_GAMEPLAY, pixelated: false, transparent: false, opacity: 1, color: new pb2HighRangeColor( 0xffffff ), color_addon: new pb2HighRangeColor( 0x000000 ), appearance: pb2SurfaceType.APPEARANCE_NORMAL, recommended_slices_per_density: 5, debris_material: pb2Entity.MATERIAL_CONCRETE, movable_sounds_preset: null, slice_texture_container: null, slice_color: new pb2HighRangeColor( 0xffffff ), slice_color_addon: new pb2HighRangeColor( 0x000000 ), slice_pixelated: false, slice_transparent: false, slice_appearance: pb2SurfaceType.APPEARANCE_NORMAL, slice_opacity: 1, slice_scale: 1, impact_scale: 1, uv_x: 0, uv_y: 0, uv_z: 0, uv_sx: 1, uv_sy: 1, uv_sz: 1 });//->Ditto->//{"operation":"create","constructor":"pb2SurfaceType.CreateSurfaceType","id":"wallSurface","geometry_type":"pb2SurfaceType.TYPE_PB2PLATFORM_WALL","texture_container":"pb2Texture.GetTextureByName('pb2platform_texture')","name":"'Ground'","terrain_generation":"false","foliage_template":"pb2FoliageClass.TEMPLATE_EARTH","has_cliff":"true","has_ground":"true","is_for_wall":"true","shader_type":"pb2SurfaceType.SHADER_GAMEPLAY","front_y":"undefined","back_y":"undefined","pixelated":"false","transparent":"false","opacity":"1","color":"new pb2HighRangeColor( 0xffffff )","color_addon":"new pb2HighRangeColor( 0x000000 )","appearance":"pb2SurfaceType.APPEARANCE_NORMAL","recommended_slices_per_density":"5","debris_material":"pb2Entity.MATERIAL_CONCRETE","movable_sounds_preset":"null","slice_texture_container":"null","slice_color":"new pb2HighRangeColor( 0xffffff )","slice_color_addon":"new pb2HighRangeColor( 0x000000 )","slice_pixelated":"false","slice_transparent":"false","slice_appearance":"pb2SurfaceType.APPEARANCE_NORMAL","slice_opacity":"1","slice_scale":"1","impact_scale":"1","x":"-810","y":"-680","_visible":"1","_locked":"0","_disabled":"0","uv_x":"0","uv_y":"0","uv_z":"0","uv_sx":"1","uv_sy":"1","uv_sz":"1"}
backgroundSurface = pb2SurfaceType.CreateSurfaceType({ geometry_type: pb2SurfaceType.TYPE_SIMPLE_BACKGROUND, texture_container: pb2Texture.GetTextureByName('mat_panel_tile'), terrain_generation: false, is_for_wall: false, shader_type: pb2SurfaceType.SHADER_GAMEPLAY, pixelated: false, transparent: false, opacity: 1, color: new pb2HighRangeColor( 0xffffff ), color_addon: new pb2HighRangeColor( 0x000000 ), appearance: pb2SurfaceType.APPEARANCE_NORMAL, recommended_slices_per_density: 5, debris_material: pb2Entity.MATERIAL_CONCRETE, movable_sounds_preset: null, slice_texture_container: null, slice_color: new pb2HighRangeColor( 0xffffff ), slice_color_addon: new pb2HighRangeColor( 0x000000 ), slice_pixelated: false, slice_transparent: false, slice_appearance: pb2SurfaceType.APPEARANCE_NORMAL, slice_opacity: 1, slice_scale: 1, uv_x: 0, uv_y: 0, uv_z: 0, uv_sx: 1, uv_sy: 1, uv_sz: 1 });//->Ditto->//{"operation":"create","constructor":"pb2SurfaceType.CreateSurfaceType","id":"backgroundSurface","geometry_type":"pb2SurfaceType.TYPE_SIMPLE_BACKGROUND","texture_container":"pb2Texture.GetTextureByName('mat_panel_tile')","name":"'Ground'","terrain_generation":"false","foliage_template":"pb2FoliageClass.TEMPLATE_EARTH","has_cliff":"true","has_ground":"true","is_for_wall":"false","shader_type":"pb2SurfaceType.SHADER_GAMEPLAY","front_y":"undefined","back_y":"undefined","pixelated":"false","transparent":"false","opacity":"1","color":"new pb2HighRangeColor( 0xffffff )","color_addon":"new pb2HighRangeColor( 0x000000 )","appearance":"pb2SurfaceType.APPEARANCE_NORMAL","recommended_slices_per_density":"5","debris_material":"pb2Entity.MATERIAL_CONCRETE","movable_sounds_preset":"null","slice_texture_container":"null","slice_color":"new pb2HighRangeColor( 0xffffff )","slice_color_addon":"new pb2HighRangeColor( 0x000000 )","slice_pixelated":"false","slice_transparent":"false","slice_appearance":"pb2SurfaceType.APPEARANCE_NORMAL","slice_opacity":"1","slice_scale":"1","impact_scale":"1","x":"-810","y":"-630","_visible":"1","_locked":"0","_disabled":"0","uv_x":"0","uv_y":"0","uv_z":"0","uv_sx":"1","uv_sy":"1","uv_sz":"1"}
pb2GameWorld.CreateBoxShape({ x: -570, y: -20, w: 670, h: 130, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-570","y":"-20","w":"670","h":"130","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: -230, y: -130, w: 360, h: 190, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-230","y":"-130","w":"360","h":"190","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: 30, y: -290, w: 220, h: 430, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"30","y":"-290","w":"220","h":"430","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: 180, y: -260, w: 400, h: 170, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"180","y":"-260","w":"400","h":"170","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: -530, y: -480, w: 750, h: 530, m: backgroundSurface, type: pb2Shape.BACKGROUND });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-530","y":"-480","w":"750","h":"530","m":"backgroundSurface","wc":"null","type":"pb2Shape.BACKGROUND","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":"","attached_to":"null"}
pb2GameWorld.CreateBoxShape({ x: 220, y: -480, w: 400, h: 320, m: backgroundSurface, type: pb2Shape.BACKGROUND });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"220","y":"-480","w":"400","h":"320","m":"backgroundSurface","wc":"null","type":"pb2Shape.BACKGROUND","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":"","attached_to":"null"}
pb2GameWorld.CreateBoxShape({ x: 220, y: -160, w: 220, h: 310, m: backgroundSurface, type: pb2Shape.BACKGROUND });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"220","y":"-160","w":"220","h":"310","m":"backgroundSurface","wc":"null","type":"pb2Shape.BACKGROUND","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":"","attached_to":"null"}
pb2GameWorld.CreateBoxShape({ x: -810, y: -380, w: 220, h: 310, m: backgroundSurface, type: pb2Shape.BACKGROUND });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-810","y":"-380","w":"220","h":"310","m":"backgroundSurface","wc":"null","type":"pb2Shape.BACKGROUND","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":"","attached_to":"null"}

/* 
    In PB3, character that has their current health less than their max health doesn't regenerate their health.

    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration
    which imitates PB2 behavior.

    If this effect is not desired, you may remove the script.
*/
pb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    In PB3, character that has their current health less than their max health doesn't regenerate their health.\n\n    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration\n    which imitates PB2 behavior.\n\n    If this effect is not desired, you may remove the script.\n*/\npb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));","x":"-760","y":"-530","_visible":"1","_locked":"0","_disabled":"0"}
pb2GameWorld.FinalizeWorld();}//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.FinalizeWorld","argument_values":"","keep_at_the_bottom":"1","_visible":"0","_locked":"0","_disabled":"0"}