var wallSurface, team, skin, aiPreset, vector, execute_method, vector_1, execute_method_1;//->Ditto->//{"operation":"define_global_vars"}
pb2GameWorld.DownloadModules( { user_data_uids_to_load: [ 183/*Eric Gurt's Basic trigger action presets*/ ], inline: true, success_callback: _pb2N } );function _pb2N(){//->Ditto->//{"id":"","operation":"create","constructor":"pb2GameWorld.DownloadModules","user_data_uids_to_load":"[ 183/*Eric Gurt's Basic trigger action presets*/ ]","execute_on_load":"true","inline":"true","success_callback":"null","error_callback":"null","x":"0","y":"0","_visible":"0","_locked":"0","_disabled":"0"}
pb2GameWorld.EnableSimplePlayerAssignmentLogic();//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.EnableSimplePlayerAssignmentLogic","argument_values":"","keep_at_the_bottom":"0","_visible":"0","_locked":"0","_disabled":"0"}

/* 
    This script changes the current setting such that it closely resembles PB2 settings. 
    You may remove this script if desired.
*/
pb2GunDisposer.normal_time_to_live=Infinity;
pb2RagdollDisposer.normal_time_to_live=Infinity;
pb2Bullet.friction_wall=0.5;
//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    This script changes the current setting such that it closely resembles PB2 settings. \n    You may remove this script if desired.\n*/\npb2GunDisposer.normal_time_to_live=Infinity;\npb2RagdollDisposer.normal_time_to_live=Infinity;\npb2Bullet.friction_wall=0.5;\n","x":"-300","y":"-250","_visible":"1","_locked":"0","_disabled":"0"}
wallSurface = pb2SurfaceType.CreateSurfaceType({ geometry_type: pb2SurfaceType.TYPE_PB2PLATFORM_WALL, texture_container: pb2Texture.GetTextureByName('pb2platform_texture'), terrain_generation: false, is_for_wall: true, shader_type: pb2SurfaceType.SHADER_GAMEPLAY, pixelated: false, transparent: false, opacity: 1, color: new pb2HighRangeColor( 0xffffff ), color_addon: new pb2HighRangeColor( 0x000000 ), appearance: pb2SurfaceType.APPEARANCE_NORMAL, recommended_slices_per_density: 5, debris_material: pb2Entity.MATERIAL_CONCRETE, movable_sounds_preset: null, slice_texture_container: null, slice_color: new pb2HighRangeColor( 0xffffff ), slice_color_addon: new pb2HighRangeColor( 0x000000 ), slice_pixelated: false, slice_transparent: false, slice_appearance: pb2SurfaceType.APPEARANCE_NORMAL, slice_opacity: 1, slice_scale: 1, impact_scale: 1, uv_x: 0, uv_y: 0, uv_z: 0, uv_sx: 1, uv_sy: 1, uv_sz: 1 });//->Ditto->//{"operation":"create","constructor":"pb2SurfaceType.CreateSurfaceType","id":"wallSurface","geometry_type":"pb2SurfaceType.TYPE_PB2PLATFORM_WALL","texture_container":"pb2Texture.GetTextureByName('pb2platform_texture')","name":"'Ground'","terrain_generation":"false","foliage_template":"pb2FoliageClass.TEMPLATE_EARTH","has_cliff":"true","has_ground":"true","is_for_wall":"true","shader_type":"pb2SurfaceType.SHADER_GAMEPLAY","front_y":"undefined","back_y":"undefined","pixelated":"false","transparent":"false","opacity":"1","color":"new pb2HighRangeColor( 0xffffff )","color_addon":"new pb2HighRangeColor( 0x000000 )","appearance":"pb2SurfaceType.APPEARANCE_NORMAL","recommended_slices_per_density":"5","debris_material":"pb2Entity.MATERIAL_CONCRETE","movable_sounds_preset":"null","slice_texture_container":"null","slice_color":"new pb2HighRangeColor( 0xffffff )","slice_color_addon":"new pb2HighRangeColor( 0x000000 )","slice_pixelated":"false","slice_transparent":"false","slice_appearance":"pb2SurfaceType.APPEARANCE_NORMAL","slice_opacity":"1","slice_scale":"1","impact_scale":"1","x":"-300","y":"-400","_visible":"1","_locked":"0","_disabled":"0","uv_x":"0","uv_y":"0","uv_z":"0","uv_sx":"1","uv_sy":"1","uv_sz":"1"}
team = pb2Team.CreateTeam({ ai_in_team: true, title: 'Alpha', hud_color: new pb2HighRangeColor( 0x6a94ff ), recolor_nicknames_on_overhead: true, friendly_fire: false, friendly_damage_multiplier: 1, normal_damage_to_dead_teammates: true, teammates_collide: false, allow_private_communication: true, overheads_visibility: pb2OverheadHUD.OVERHEAD_VISIBILITY_TEAMMATES_ONLY });//->Ditto->//{"operation":"create","constructor":"pb2Team.CreateTeam","id":"team","ai_in_team":"true","title":"'Alpha'","hud_color":"new pb2HighRangeColor( 0x6a94ff )","recolor_nicknames_on_overhead":"true","friendly_fire":"false","friendly_damage_multiplier":"1","normal_damage_to_dead_teammates":"true","teammates_collide":"false","allow_private_communication":"true","overheads_visibility":"pb2OverheadHUD.OVERHEAD_VISIBILITY_TEAMMATES_ONLY","x":"-300","y":"-500","_visible":"1","_locked":"0","_disabled":"0"}
skin = pb2SkinEditor.SpawnDefaultSkin( 1 );//->Ditto->//{"operation":"create","constructor":"pb2SkinEditor.SpawnDefaultSkin","id":"skin","type":"pb2SkinEditor.SKIN_TYPE_DEFAULT","frame":"1","user_data_uid":"-1","user_data_uid_title":"","x":"-300","y":"-550","_visible":"1","_locked":"0","_disabled":"0"}
aiPreset = { skill: 1, behavior: pb2AIModule.BEHAVIOR_MPBOT, allow_trace_shots: true, allow_hit_reporting: true, factor_for_team_damage_paths_avoidance: 1, rejection_point_for_team_damage_paths: Infinity, hunt_attacker: true, hunt_seen_threats: true, hunt_random_known_threats_range: 200, heal_teammates: true, hear_range: 0, sequence_behavior: pb2AIModule.SEQUENCE_BEHAVIOR_SERIOUS };//->Ditto->//{"operation":"create","constructor":"Object.AIPreset","id":"aiPreset","skill":"1","behavior":"pb2AIModule.BEHAVIOR_MPBOT","allow_trace_shots":"true","allow_hit_reporting":"true","factor_for_team_damage_paths_avoidance":"1","rejection_point_for_team_damage_paths":"Infinity","hunt_attacker":"true","hunt_seen_threats":"true","hunt_random_known_threats_range":"200","heal_teammates":"true","hear_range":"0","x":"-300","y":"-600","_visible":"1","_locked":"0","_disabled":"0","sequence_behavior":"pb2AIModule.SEQUENCE_BEHAVIOR_SERIOUS"}
group_tool = ( rigid_body )=>//->Ditto->//{"operation":"layer_definition","id":"group_tool","availability":"global","arguments":"rigid_body","is_open":true,"close_when_possible":false,"enabled":"1","max_calls":"Infinity","auto_spawn":"0","auto_spawn_arguments":"","fail_call_callback":"null","fail_call_callback_same_arguments":"1","children_properties_to_rewrite":"","x":"-150","y":"-100","_visible":"1","_locked":"0","_disabled":"0","_test_call":"TestExec","_test_call_argument_values":""}
{//->Ditto->//{"operation":"open_layer_bracket"}
vector = new Vector({ x: -50, y: -100, dx: 0, dy: -100 });//->Ditto->//{"id":"vector","operation":"create","constructor":"new Vector","x":"-50","y":"-100","dx":"0","dy":"-100","_visible":"1","_locked":"0","_disabled":"0"}
globalThis.ApplyPushForceLogicToBody(rigid_body, vector);//->Ditto->//{"operation":"call_method","method":"globalThis.ApplyPushForceLogicToBody","argument_values":"","keep_at_the_bottom":"0","x":"-100","y":"-100","_visible":"1","_locked":"0","_disabled":"0","attr0":"rigid_body","attr1":"vector"}
};group_tool=_pb2T(group_tool,1,Infinity,null,1);//->Ditto->//{"operation":"close_layer_bracket"}
group_tool_1 = ( rigid_body )=>//->Ditto->//{"operation":"layer_definition","id":"group_tool_1","availability":"global","arguments":"rigid_body","is_open":true,"close_when_possible":false,"enabled":"1","max_calls":"Infinity","auto_spawn":"0","auto_spawn_arguments":"","fail_call_callback":"null","fail_call_callback_same_arguments":"1","children_properties_to_rewrite":"","x":"50","y":"-100","_visible":"1","_locked":"0","_disabled":"0","_test_call":"TestExec","_test_call_argument_values":""}
{//->Ditto->//{"operation":"open_layer_bracket"}
vector_1 = new Vector({ x: 150, y: -100, dx: 100, dy: 100 });//->Ditto->//{"id":"vector_1","operation":"create","constructor":"new Vector","x":"150","y":"-100","dx":"100","dy":"100","_visible":"1","_locked":"0","_disabled":"0"}
globalThis.ApplyPushForceLogicToBody(rigid_body, vector_1);//->Ditto->//{"operation":"call_method","method":"globalThis.ApplyPushForceLogicToBody","argument_values":"","keep_at_the_bottom":"0","x":"100","y":"-100","_visible":"1","_locked":"0","_disabled":"0","attr0":"rigid_body","attr1":"vector_1"}
};group_tool_1=_pb2T(group_tool_1,1,Infinity,null,1);//->Ditto->//{"operation":"close_layer_bracket"}
pb2GameWorld.CreateBoxShape({ x: -300, y: 0, w: 600, h: 100, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-300","y":"0","w":"600","h":"100","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: 50, y: -20, w: 100, h: 120, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"50","y":"-20","w":"100","h":"120","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: -150, y: -200, w: 100, h: 200, type: pb2Shape.REGION });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-150","y":"-200","w":"100","h":"200","m":"null","wc":"null","type":"pb2Shape.REGION","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":"","attached_to":"null","increased_accuracy":"false","react_to_ragdolls":"true","react_to_guns":"true","react_to_bullets":"true","react_to_grenades":"true","react_to_grappling_hooks":"true","react_to_shields":"true","react_to_entities":"false","react_to_exact_movables":"false","onEnter":"null","onLeave":"null","onSubstep":"group_tool"}
pb2GameWorld.CreateBoxShape({ x: 50, y: -200, w: 100, h: 200, type: pb2Shape.REGION });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"50","y":"-200","w":"100","h":"200","m":"null","wc":"null","type":"pb2Shape.REGION","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":"","attached_to":"null","increased_accuracy":"false","react_to_ragdolls":"true","react_to_guns":"true","react_to_bullets":"true","react_to_grenades":"true","react_to_grappling_hooks":"true","react_to_shields":"true","react_to_entities":"false","react_to_exact_movables":"false","onEnter":"null","onLeave":"null","onSubstep":"group_tool_1"}
pb2Ragdoll.CreateRagdollComplete({ x: -230, y: 0, skin: skin, team: team, vision: pb2Vision.VISION_DIRECTED_TRACE, style_boost: pb2StyleBoost.SELFBOOST, style_swords: pb2StyleSwords.BASIC, driver_of: null, sword_projectile_reflection: true, hmax: 130, can_be_revived: true, can_breathe_in_water: true, can_breathe_in_toxic_clouds: false, hmax_damage_multiplier: 0, regen_module: pb2StyleRegen.style_delayed_speedup, drop_guns_on_death: pb2Character.DROP_ALWAYS, drop_grenades_on_death: pb2Character.DROP_WHEN_INTENDED_ONLY, enforce_skin_limitations: false, use_skin_properties: false, player_controllable: true, ai_preset: aiPreset, side: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Ragdoll.CreateRagdollComplete","id":"","x":"-230","y":"0","tox":"0","toy":"0","rotation":"0 / 180 * Math.PI","stability":"1","scale":"1","skin":"skin","team":"team","vision":"pb2Vision.VISION_DIRECTED_TRACE","style_boost":"pb2StyleBoost.SELFBOOST","style_grappling_hook":"undefined","style_swords":"pb2StyleSwords.BASIC","driver_of":"null","name":"undefined","sword_projectile_reflection":"true","hmax":"130","start_hea":"undefined","hea":"undefined","can_be_revived":"true","can_breathe_in_water":"true","can_breathe_in_toxic_clouds":"false","hmax_damage_multiplier":"0","regen_module":"pb2StyleRegen.style_delayed_speedup","onDeath":"null","drop_guns_on_death":"pb2Character.DROP_ALWAYS","drop_grenades_on_death":"pb2Character.DROP_WHEN_INTENDED_ONLY","enforce_skin_limitations":"false","use_skin_properties":"false","player_controllable":"true","ai_preset":"aiPreset","_visible":"1","_locked":"0","_disabled":"0","side":"1"}

/* 
    In PB3, character that has their current health less than their max health doesn't regenerate their health.

    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration
    which imitates PB2 behavior.

    If this effect is not desired, you may remove the script.
*/
pb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    In PB3, character that has their current health less than their max health doesn't regenerate their health.\n\n    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration\n    which imitates PB2 behavior.\n\n    If this effect is not desired, you may remove the script.\n*/\npb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));","x":"-250","y":"-250","_visible":"1","_locked":"0","_disabled":"0"}
pb2GameWorld.FinalizeWorld();}//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.FinalizeWorld","argument_values":"","keep_at_the_bottom":"1","_visible":"0","_locked":"0","_disabled":"0"}