var wallSurface, team, skin, aiPreset;//->Ditto->//{"operation":"define_global_vars"}
pb2GameWorld.DownloadModules( { user_data_uids_to_load: [ 183/*Eric Gurt's Basic trigger action presets*/ ], inline: true, success_callback: _pb2N } );function _pb2N(){//->Ditto->//{"id":"","operation":"create","constructor":"pb2GameWorld.DownloadModules","user_data_uids_to_load":"[ 183/*Eric Gurt's Basic trigger action presets*/ ]","execute_on_load":"true","inline":"true","success_callback":"null","error_callback":"null","x":"0","y":"0","_visible":"0","_locked":"0","_disabled":"0"}
pb2GameWorld.EnableSimplePlayerAssignmentLogic();//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.EnableSimplePlayerAssignmentLogic","argument_values":"","keep_at_the_bottom":"0","_visible":"0","_locked":"0","_disabled":"0"}

/* 
    This script changes the current setting such that it closely resembles PB2 settings. 
    You may remove this script if desired.
*/
pb2GunDisposer.normal_time_to_live=Infinity;
pb2RagdollDisposer.normal_time_to_live=Infinity;
pb2Bullet.friction_wall=0.5;
//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    This script changes the current setting such that it closely resembles PB2 settings. \n    You may remove this script if desired.\n*/\npb2GunDisposer.normal_time_to_live=Infinity;\npb2RagdollDisposer.normal_time_to_live=Infinity;\npb2Bullet.friction_wall=0.5;\n","x":"-600","y":"-50","_visible":"1","_locked":"0","_disabled":"0"}
wallSurface = pb2SurfaceType.CreateSurfaceType({ geometry_type: pb2SurfaceType.TYPE_PB2PLATFORM_WALL, texture_container: pb2Texture.GetTextureByName('pb2platform_texture'), terrain_generation: false, is_for_wall: true, shader_type: pb2SurfaceType.SHADER_GAMEPLAY, pixelated: false, transparent: false, opacity: 1, color: new pb2HighRangeColor( 0xffffff ), color_addon: new pb2HighRangeColor( 0x000000 ), appearance: pb2SurfaceType.APPEARANCE_NORMAL, recommended_slices_per_density: 5, debris_material: pb2Entity.MATERIAL_CONCRETE, movable_sounds_preset: null, slice_texture_container: null, slice_color: new pb2HighRangeColor( 0xffffff ), slice_color_addon: new pb2HighRangeColor( 0x000000 ), slice_pixelated: false, slice_transparent: false, slice_appearance: pb2SurfaceType.APPEARANCE_NORMAL, slice_opacity: 1, slice_scale: 1, impact_scale: 1, uv_x: 0, uv_y: 0, uv_z: 0, uv_sx: 1, uv_sy: 1, uv_sz: 1 });//->Ditto->//{"operation":"create","constructor":"pb2SurfaceType.CreateSurfaceType","id":"wallSurface","geometry_type":"pb2SurfaceType.TYPE_PB2PLATFORM_WALL","texture_container":"pb2Texture.GetTextureByName('pb2platform_texture')","name":"'Ground'","terrain_generation":"false","foliage_template":"pb2FoliageClass.TEMPLATE_EARTH","has_cliff":"true","has_ground":"true","is_for_wall":"true","shader_type":"pb2SurfaceType.SHADER_GAMEPLAY","front_y":"undefined","back_y":"undefined","pixelated":"false","transparent":"false","opacity":"1","color":"new pb2HighRangeColor( 0xffffff )","color_addon":"new pb2HighRangeColor( 0x000000 )","appearance":"pb2SurfaceType.APPEARANCE_NORMAL","recommended_slices_per_density":"5","debris_material":"pb2Entity.MATERIAL_CONCRETE","movable_sounds_preset":"null","slice_texture_container":"null","slice_color":"new pb2HighRangeColor( 0xffffff )","slice_color_addon":"new pb2HighRangeColor( 0x000000 )","slice_pixelated":"false","slice_transparent":"false","slice_appearance":"pb2SurfaceType.APPEARANCE_NORMAL","slice_opacity":"1","slice_scale":"1","impact_scale":"1","x":"-600","y":"-200","_visible":"1","_locked":"0","_disabled":"0","uv_x":"0","uv_y":"0","uv_z":"0","uv_sx":"1","uv_sy":"1","uv_sz":"1"}
team = pb2Team.CreateTeam({ ai_in_team: true, title: 'Alpha', hud_color: new pb2HighRangeColor( 0x6a94ff ), recolor_nicknames_on_overhead: true, friendly_fire: false, friendly_damage_multiplier: 1, normal_damage_to_dead_teammates: true, teammates_collide: false, allow_private_communication: true, overheads_visibility: pb2OverheadHUD.OVERHEAD_VISIBILITY_TEAMMATES_ONLY });//->Ditto->//{"operation":"create","constructor":"pb2Team.CreateTeam","id":"team","ai_in_team":"true","title":"'Alpha'","hud_color":"new pb2HighRangeColor( 0x6a94ff )","recolor_nicknames_on_overhead":"true","friendly_fire":"false","friendly_damage_multiplier":"1","normal_damage_to_dead_teammates":"true","teammates_collide":"false","allow_private_communication":"true","overheads_visibility":"pb2OverheadHUD.OVERHEAD_VISIBILITY_TEAMMATES_ONLY","x":"-600","y":"-300","_visible":"1","_locked":"0","_disabled":"0"}
skin = pb2SkinEditor.SpawnDefaultSkin( 1 );//->Ditto->//{"operation":"create","constructor":"pb2SkinEditor.SpawnDefaultSkin","id":"skin","type":"pb2SkinEditor.SKIN_TYPE_DEFAULT","frame":"1","user_data_uid":"-1","user_data_uid_title":"","x":"-600","y":"-350","_visible":"1","_locked":"0","_disabled":"0"}
aiPreset = { skill: 1, behavior: pb2AIModule.BEHAVIOR_MPBOT, allow_trace_shots: true, allow_hit_reporting: true, factor_for_team_damage_paths_avoidance: 1, rejection_point_for_team_damage_paths: Infinity, hunt_attacker: true, hunt_seen_threats: true, hunt_random_known_threats_range: 200, heal_teammates: true, hear_range: 0, sequence_behavior: pb2AIModule.SEQUENCE_BEHAVIOR_SERIOUS };//->Ditto->//{"operation":"create","constructor":"Object.AIPreset","id":"aiPreset","skill":"1","behavior":"pb2AIModule.BEHAVIOR_MPBOT","allow_trace_shots":"true","allow_hit_reporting":"true","factor_for_team_damage_paths_avoidance":"1","rejection_point_for_team_damage_paths":"Infinity","hunt_attacker":"true","hunt_seen_threats":"true","hunt_random_known_threats_range":"200","heal_teammates":"true","hear_range":"0","x":"-600","y":"-400","_visible":"1","_locked":"0","_disabled":"0","sequence_behavior":"pb2AIModule.SEQUENCE_BEHAVIOR_SERIOUS"}
pb2GameWorld.CreateBoxShape({ x: -600, y: 0, w: 1200, h: 300, m: wallSurface, type: pb2Shape.WALL });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-600","y":"0","w":"1200","h":"300","m":"wallSurface","wc":"null","type":"pb2Shape.WALL","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2Ragdoll.CreateRagdollComplete({ x: -530, y: 0, skin: skin, team: team, vision: pb2Vision.VISION_DIRECTED_TRACE, style_boost: pb2StyleBoost.SELFBOOST, style_swords: pb2StyleSwords.BASIC, driver_of: null, sword_projectile_reflection: true, hmax: 130, can_be_revived: true, can_breathe_in_water: true, can_breathe_in_toxic_clouds: false, hmax_damage_multiplier: 0, regen_module: pb2StyleRegen.style_delayed_speedup, drop_guns_on_death: pb2Character.DROP_ALWAYS, drop_grenades_on_death: pb2Character.DROP_WHEN_INTENDED_ONLY, enforce_skin_limitations: false, use_skin_properties: false, player_controllable: true, ai_preset: aiPreset, side: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Ragdoll.CreateRagdollComplete","id":"","x":"-530","y":"0","tox":"0","toy":"0","rotation":"0 / 180 * Math.PI","stability":"1","scale":"1","skin":"skin","team":"team","vision":"pb2Vision.VISION_DIRECTED_TRACE","style_boost":"pb2StyleBoost.SELFBOOST","style_grappling_hook":"undefined","style_swords":"pb2StyleSwords.BASIC","driver_of":"null","name":"undefined","sword_projectile_reflection":"true","hmax":"130","start_hea":"undefined","hea":"undefined","can_be_revived":"true","can_breathe_in_water":"true","can_breathe_in_toxic_clouds":"false","hmax_damage_multiplier":"0","regen_module":"pb2StyleRegen.style_delayed_speedup","onDeath":"null","drop_guns_on_death":"pb2Character.DROP_ALWAYS","drop_grenades_on_death":"pb2Character.DROP_WHEN_INTENDED_ONLY","enforce_skin_limitations":"false","use_skin_properties":"false","player_controllable":"true","ai_preset":"aiPreset","_visible":"1","_locked":"0","_disabled":"0","side":"1"}
pb2Entity.CreateEntity({ x: 470, y: -20, type: pb2Entity.TYPE_BARREL , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"470","y":"-20","type":"pb2Entity.TYPE_BARREL ","team":"null","creator_ragdoll":"null","style_id":"pb2EntityBarrel.STYLE_ID_YELLOW","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: 510, y: -20, type: pb2Entity.TYPE_BARREL , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"510","y":"-20","type":"pb2Entity.TYPE_BARREL ","team":"null","creator_ragdoll":"null","style_id":"pb2EntityBarrel.STYLE_ID_BLUE","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: 550, y: -20, type: pb2Entity.TYPE_BARREL , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"550","y":"-20","type":"pb2Entity.TYPE_BARREL ","team":"null","creator_ragdoll":"null","style_id":"pb2EntityBarrel.STYLE_ID_RED","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: -400, y: -80, type: pb2Entity.TYPE_MOTO , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"-400","y":"-80","type":"pb2Entity.TYPE_MOTO ","team":"null","creator_ragdoll":"null","style_id":"pb2EntityMoto.STYLE_ID_MOBILE_CS","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: -150, y: -200, type: pb2Entity.TYPE_WALKER , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"-150","y":"-200","type":"pb2Entity.TYPE_WALKER ","team":"null","creator_ragdoll":"null","style_id":"1","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: 30, y: -30, type: pb2Entity.TYPE_CRATE , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"30","y":"-30","type":"pb2Entity.TYPE_CRATE ","team":"null","creator_ragdoll":"null","style_id":"1","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: 120, y: -30, type: pb2Entity.TYPE_CORVETTE , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 0.2, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"120","y":"-30","type":"pb2Entity.TYPE_CORVETTE ","team":"null","creator_ragdoll":"null","style_id":"pb2EntityMoto.STYLE_ID_MOBILE_CS","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"0.2","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}
pb2Entity.CreateEntity({ x: 310, y: -100, type: pb2Entity.TYPE_CORVETTE , side: 1, driver_can_enter: true, driver_can_leave: true, scale: 1, multiply_health: 1 });//->Ditto->//{"operation":"create","constructor":"pb2Entity.CreateEntity","id":"","x":"310","y":"-100","type":"pb2Entity.TYPE_CORVETTE ","team":"null","creator_ragdoll":"null","style_id":"pb2EntityMoto.STYLE_ID_MOBILE_CS","tox":"0","toy":"0","side":"1","rotation":"0 / 180 * Math.PI","onDeath":"null","driver_can_enter":"true","driver_can_leave":"true","scale":"1","multiply_health":"1","_visible":"1","_locked":"0","_disabled":"0","gun":"null","range":"undefined","strength":"1","mass_cap_scale":"1","cooldown_duration_scale":"1","can_be_damaged":"true","act_x":"0","act_y":"0","time_to_live":"0"}

/* 
    In PB3, character that has their current health less than their max health doesn't regenerate their health.

    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration
    which imitates PB2 behavior.

    If this effect is not desired, you may remove the script.
*/
pb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    In PB3, character that has their current health less than their max health doesn't regenerate their health.\n\n    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration\n    which imitates PB2 behavior.\n\n    If this effect is not desired, you may remove the script.\n*/\npb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));","x":"-550","y":"-50","_visible":"1","_locked":"0","_disabled":"0"}
pb2GameWorld.FinalizeWorld();}//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.FinalizeWorld","argument_values":"","keep_at_the_bottom":"1","_visible":"0","_locked":"0","_disabled":"0"}