var liquidKind, liquidKind_1, liquidKind_2, liquidKind_3;//->Ditto->//{"operation":"define_global_vars"}
pb2GameWorld.DownloadModules( { user_data_uids_to_load: [ 183/*Eric Gurt's Basic trigger action presets*/ ], inline: true, success_callback: _pb2N } );function _pb2N(){//->Ditto->//{"id":"","operation":"create","constructor":"pb2GameWorld.DownloadModules","user_data_uids_to_load":"[ 183/*Eric Gurt's Basic trigger action presets*/ ]","execute_on_load":"true","inline":"true","success_callback":"null","error_callback":"null","x":"0","y":"0","_visible":"0","_locked":"0","_disabled":"0"}
pb2GameWorld.EnableSimplePlayerAssignmentLogic();//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.EnableSimplePlayerAssignmentLogic","argument_values":"","keep_at_the_bottom":"0","_visible":"0","_locked":"0","_disabled":"0"}

/* 
    This script changes the current setting such that it closely resembles PB2 settings. 
    You may remove this script if desired.
*/
pb2GunDisposer.normal_time_to_live=Infinity;
pb2RagdollDisposer.normal_time_to_live=Infinity;
pb2Bullet.friction_wall=0.5;
//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    This script changes the current setting such that it closely resembles PB2 settings. \n    You may remove this script if desired.\n*/\npb2GunDisposer.normal_time_to_live=Infinity;\npb2RagdollDisposer.normal_time_to_live=Infinity;\npb2Bullet.friction_wall=0.5;\n","x":"-230","y":"-150","_visible":"1","_locked":"0","_disabled":"0"}
liquidKind = pb2WaterClass.DeclareWaterClass({ reflection: 0.8, color: 0x003344, opacity: 0, glow: false, allow_fixed: true, viscosity: 1, density: 1, extend_left: false, extend_right: false, cover_decals: false, type: pb2WaterClass.TYPE_WATER });//->Ditto->//{"operation":"create","constructor":"pb2WaterClass.DeclareWaterClass","id":"liquidKind","reflection":"0.8","color":"0x003344","opacity":"0","glow":"false","allow_fixed":"true","viscosity":"1","density":"1","depth":"undefined","depth_front":"undefined","extend_left":"false","extend_right":"false","cover_decals":"false","type":"pb2WaterClass.TYPE_WATER","damage_scale":"0","fire_color":"new pb2HighRangeColor( 0x723f26 )","x":"-230","y":"-350","_visible":"1","_locked":"0","_disabled":"0"}
liquidKind_1 = pb2WaterClass.DeclareWaterClass({ reflection: 0.8, color: 0x003344, opacity: 0.6, glow: false, allow_fixed: true, viscosity: 1, density: 1, extend_left: false, extend_right: false, cover_decals: false, type: pb2WaterClass.TYPE_WATER });//->Ditto->//{"operation":"create","constructor":"pb2WaterClass.DeclareWaterClass","id":"liquidKind_1","reflection":"0.8","color":"0x003344","opacity":"0.6","glow":"false","allow_fixed":"true","viscosity":"1","density":"1","depth":"undefined","depth_front":"undefined","extend_left":"false","extend_right":"false","cover_decals":"false","type":"pb2WaterClass.TYPE_WATER","damage_scale":"0","fire_color":"new pb2HighRangeColor( 0x723f26 )","x":"-180","y":"-350","_visible":"1","_locked":"0","_disabled":"0"}
liquidKind_2 = pb2WaterClass.DeclareWaterClass({ reflection: 0.8, color: 0x66ff00, opacity: 0.6, glow: false, allow_fixed: true, viscosity: 1, density: 1, extend_left: false, extend_right: false, cover_decals: false, type: pb2WaterClass.TYPE_TOXIC });//->Ditto->//{"operation":"create","constructor":"pb2WaterClass.DeclareWaterClass","id":"liquidKind_2","reflection":"0.8","color":"0x66ff00","opacity":"0.6","glow":"false","allow_fixed":"true","viscosity":"1","density":"1","depth":"undefined","depth_front":"undefined","extend_left":"false","extend_right":"false","cover_decals":"false","type":"pb2WaterClass.TYPE_TOXIC","damage_scale":"0.01","fire_color":"new pb2HighRangeColor( 0x723f26 )","x":"-130","y":"-350","_visible":"1","_locked":"0","_disabled":"0"}
liquidKind_3 = pb2WaterClass.DeclareWaterClass({ reflection: 0.8, color: 0x66ff00, opacity: 0, glow: false, allow_fixed: true, viscosity: 1, density: 1, extend_left: false, extend_right: false, cover_decals: false, type: pb2WaterClass.TYPE_TOXIC });//->Ditto->//{"operation":"create","constructor":"pb2WaterClass.DeclareWaterClass","id":"liquidKind_3","reflection":"0.8","color":"0x66ff00","opacity":"0","glow":"false","allow_fixed":"true","viscosity":"1","density":"1","depth":"undefined","depth_front":"undefined","extend_left":"false","extend_right":"false","cover_decals":"false","type":"pb2WaterClass.TYPE_TOXIC","damage_scale":"0.01","fire_color":"new pb2HighRangeColor( 0x723f26 )","x":"-80","y":"-350","_visible":"1","_locked":"0","_disabled":"0"}
pb2GameWorld.CreateBoxShape({ x: -230, y: -100, w: 100, h: 100, wc: liquidKind, type: pb2Shape.WATER });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-230","y":"-100","w":"100","h":"100","m":"null","wc":"liquidKind","type":"pb2Shape.WATER","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: -110, y: -100, w: 100, h: 100, wc: liquidKind_1, type: pb2Shape.WATER });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"-110","y":"-100","w":"100","h":"100","m":"null","wc":"liquidKind_1","type":"pb2Shape.WATER","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: 10, y: -100, w: 100, h: 100, wc: liquidKind_2, type: pb2Shape.WATER });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"10","y":"-100","w":"100","h":"100","m":"null","wc":"liquidKind_2","type":"pb2Shape.WATER","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}
pb2GameWorld.CreateBoxShape({ x: 130, y: -100, w: 100, h: 100, wc: liquidKind_3, type: pb2Shape.WATER });//->Ditto->//{"operation":"create","constructor":"pb2GameWorld.CreateBoxShape","x":"130","y":"-100","w":"100","h":"100","m":"null","wc":"liquidKind_3","type":"pb2Shape.WATER","corner":"pb2Shape.CORNER_NONE","dots":"null","_points_being_edited":false,"_visible":"1","_locked":"0","_disabled":"0","id":""}

/* 
    In PB3, character that has their current health less than their max health doesn't regenerate their health.

    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration
    which imitates PB2 behavior.

    If this effect is not desired, you may remove the script.
*/
pb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));//->Ditto->//{"operation":"code","snippet_color":"0xb1b1ff","code":"\n/* \n    In PB3, character that has their current health less than their max health doesn't regenerate their health.\n\n    This script damages all PB3 character that doesn't have max health with a value of 0, forcing health regeneration\n    which imitates PB2 behavior.\n\n    If this effect is not desired, you may remove the script.\n*/\npb2Character.characters.filter(c=>c.hea!==c.hmax&&c.hea>0).forEach(c=>c.SubstractHealth(0));","x":"-180","y":"-150","_visible":"1","_locked":"0","_disabled":"0"}
pb2GameWorld.FinalizeWorld();}//->Ditto->//{"x":"0","y":"0","operation":"call_method","method":"pb2GameWorld.FinalizeWorld","argument_values":"","keep_at_the_bottom":"1","_visible":"0","_locked":"0","_disabled":"0"}